/**
 * canonical-notes.json (9.70.0) — the canonical wire strings, as DATA.
 *
 * The property under test is that the JSON cannot lie. `absent()`,
 * `coverage()` and `describedResult()` mint shapes carrying a static note and a
 * reserved marker key, and those bytes are a contract: a strict recognizer
 * takes the marker verbatim, and the note is what the docs promise a model
 * reads. A tool written in another language has to reproduce them exactly —
 * and the only door the package offered was the compiled ESM, which a Python
 * sidecar in the field duly regex-scraped at import time. Right instinct
 * (read the value, never copy it), wrong door, and the wrong door was ours.
 *
 * So there are exactly two ways this file can be wrong, and both are pinned:
 * the JSON could disagree with the constants (it is GENERATED from the built
 * barrel, so this suite proves the generated bytes really do match), or it
 * could fail to reach the consumer at all (so this suite unpacks the real
 * tarball and reads it back out).
 *
 * Sections follow Convention 3: Unit (shape and non-emptiness) · Integration
 * (byte equality with the exported constants — the anti-drift pin) ·
 * Packaging (the tarball really carries it, and the exports map really
 * resolves it) · Documentation (the published path and the Python example
 * name the file that exists) · Regression (the generator stays wired into
 * `npm run build`, which is what makes drift impossible rather than unlikely).
 *
 * COST NOTE: the packaging section runs a real `npm pack`. It is the slowest
 * test in this directory and it is deliberate — a `files` whitelist typo is
 * invisible to every other check in the repo and is discovered by a consumer.
 */

import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  ABSENCE_MARKER,
  ABSENCE_NOTE,
  absent,
  coverage,
  COVERAGE_BLOCK_HEADING,
  COVERAGE_MARKER,
  COVERAGE_NOTE,
  IN_PROGRESS_WIRE,
  PERIOD_WIRE,
  readCoverageResult,
  SEMANTICS_MARKER,
  SEMANTICS_NOTE,
} from '../../src/index.js';

const ROOT = join(__dirname, '../..');
const JSON_PATH = join(ROOT, 'canonical-notes.json');
/** The path this package PROMISES, relative to its own root. Documented. */
const PUBLISHED_PATH = 'canonical-notes.json';

interface CanonicalNotes {
  readonly $comment: string;
  readonly notes: Record<string, string>;
  readonly markers: Record<string, string>;
  readonly headings: Record<string, string>;
  /** Constants published WHOLE (honesty step 7b): the period's wire spelling. */
  readonly wire: Record<string, Record<string, string>>;
}

const load = (): CanonicalNotes => JSON.parse(readFileSync(JSON_PATH, 'utf-8')) as CanonicalNotes;

/** Constant name → the value the built package exports under it. */
const EXPORTED: Readonly<Record<string, string>> = {
  ABSENCE_NOTE,
  COVERAGE_NOTE,
  SEMANTICS_NOTE,
  ABSENCE_MARKER,
  COVERAGE_MARKER,
  SEMANTICS_MARKER,
  COVERAGE_BLOCK_HEADING,
};

// ─── 1. Unit — the shape a consumer is told to expect ─────────────────

describe('unit — the file is there, it parses, and every value is a usable string', () => {
  it('carries the three groups, keyed by the exported constant names', () => {
    const data = load();
    expect(Object.keys(data.notes).sort()).toEqual([
      'ABSENCE_NOTE',
      'COVERAGE_NOTE',
      'SEMANTICS_NOTE',
    ]);
    expect(Object.keys(data.markers).sort()).toEqual([
      'ABSENCE_MARKER',
      'COVERAGE_MARKER',
      'SEMANTICS_MARKER',
    ]);
    expect(Object.keys(data.headings)).toEqual(['COVERAGE_BLOCK_HEADING']);
    expect(Object.keys(data.wire)).toEqual(['PERIOD_WIRE', 'IN_PROGRESS_WIRE']);
  });

  it('the period’s wire spelling: every reserved key and the literal unknown (honesty step 7b)', () => {
    // What a Python helper needs to mint `period` byte for byte — read, never copied.
    expect(load().wire.PERIOD_WIRE).toEqual({
      key: 'period',
      queried: 'queried',
      held: 'held',
      from: 'from',
      to: 'to',
      readAt: 'read_at',
      heldUnknown: 'unknown',
    });
  });

  it('says out loud that it is generated — an editable-looking file invites a hand edit', () => {
    expect(load().$comment).toContain('GENERATED');
    expect(load().$comment).toContain('gen-canonical-notes');
  });

  it('every value is a non-empty string (a hole here is a sidecar emitting nothing)', () => {
    const data = load();
    for (const group of [data.notes, data.markers, data.headings]) {
      for (const [name, value] of Object.entries(group)) {
        expect(typeof value, `${name} is not a string`).toBe('string');
        expect(value.length, `${name} is empty`).toBeGreaterThan(0);
      }
    }
  });
});

// ─── 2. Integration — the anti-drift pin ──────────────────────────────

describe('integration — every published value byte-equals the exported constant', () => {
  const data = load();
  const published: Record<string, string> = {
    ...data.notes,
    ...data.markers,
    ...data.headings,
  };

  it('IN_PROGRESS_WIRE — the JSON and the barrel are the same object of strings', () => {
    expect(
      data.wire.IN_PROGRESS_WIRE,
      'canonical-notes.json is stale for IN_PROGRESS_WIRE — run `npm run build` after editing it.',
    ).toEqual({ ...IN_PROGRESS_WIRE });
    expect(data.wire.IN_PROGRESS_WIRE).toEqual({ key: 'in_progress', count: 'count' });
  });

  it('IN_PROGRESS_WIRE round trip — a ledger minted from the JSON alone is read back as declared', () => {
    const w = data.wire.IN_PROGRESS_WIRE;
    const handMinted = {
      [data.markers.COVERAGE_MARKER]: {
        checked: [{ what: 'every replication session on the array' }],
        [w.key]: [{ what: 'sessions still synchronizing', [w.count]: 96 }],
        note: data.notes.COVERAGE_NOTE,
      },
      result: { failed: 0, settled: 135 },
    };
    const minted = JSON.parse(
      JSON.stringify(
        coverage(
          { failed: 0, settled: 135 },
          {
            checked: ['every replication session on the array'],
            inProgress: [{ what: 'sessions still synchronizing', count: 96 }],
          },
        ),
      ),
    ) as unknown;
    expect(minted).toEqual(handMinted);
    expect(readCoverageResult(handMinted)?.declared[0]?.inProgress).toEqual([
      { what: 'sessions still synchronizing', count: 96 },
    ]);
  });

  it('PERIOD_WIRE — the JSON and the barrel are the same object of strings', () => {
    expect(
      data.wire.PERIOD_WIRE,
      'canonical-notes.json is stale for PERIOD_WIRE — run `npm run build` after editing it.',
    ).toEqual({ ...PERIOD_WIRE });
  });

  it('PERIOD_WIRE round trip — a period minted from the JSON alone is the one the library mints and reads', () => {
    // What a helper in another language does: every key from the published
    // file, nothing typed from memory. The library's own mint must produce the
    // same object, and the recognizer must read it back as declared.
    const w = data.wire.PERIOD_WIRE;
    const queried = { from: '2026-09-26T09:00:00Z', to: '2026-09-26T10:00:00Z' };
    const held = { from: '2026-08-27T02:00:00Z', to: '2026-09-26T02:00:00Z' };
    const readAt = '2026-09-26T10:00:03Z';
    const byHand = (heldValue: unknown) => ({
      [w.queried]: { [w.from]: queried.from, [w.to]: queried.to },
      [w.held]: heldValue,
      [w.readAt]: readAt,
    });
    for (const [declared, wire] of [
      [held, byHand({ [w.from]: held.from, [w.to]: held.to })],
      ['unknown', byHand(w.heldUnknown)],
    ] as const) {
      const minted = JSON.parse(
        JSON.stringify(
          absent({
            what: 'failed backup runs',
            checked: ['every job in the 02:00 export'],
            period: { queried, held: declared, readAt },
          }),
        ),
      ) as Record<string, unknown>;
      expect(minted[w.key]).toEqual(wire);
      const handMinted = {
        [data.markers.ABSENCE_MARKER]: true,
        checked: [{ what: 'every job in the 02:00 export' }],
        [w.key]: wire,
        note: data.notes.ABSENCE_NOTE,
      };
      expect(readCoverageResult(handMinted)?.declared[0]?.period).toEqual({
        queried,
        held: declared,
        readAt,
      });
    }
  });

  for (const [name, value] of Object.entries(EXPORTED)) {
    it(`${name} — the JSON and the barrel are the same bytes`, () => {
      expect(
        published[name],
        `canonical-notes.json is stale for ${name}. It is generated from the BUILT package, ` +
          `so run \`npm run build\` after editing the constant.`,
      ).toBe(value);
    });
  }

  it('publishes nothing the barrel does not export — no invented canon', () => {
    // The other direction. A key here that no constant backs would be a
    // string a consumer trusts and the library never mints.
    expect(Object.keys(published).sort()).toEqual(Object.keys(EXPORTED).sort());
  });

  it('the notes are never interpolated, so they are safe to publish at all', () => {
    // The one property that makes a static file the right shape for this: if
    // any note quoted a caller's data, a published copy would be a lie for
    // every run but one. Pinned by re-reading the constants themselves.
    expect(ABSENCE_NOTE).not.toMatch(/\$\{|%s|\{\{/);
    expect(COVERAGE_NOTE).not.toMatch(/\$\{|%s|\{\{/);
    expect(SEMANTICS_NOTE).not.toMatch(/\$\{|%s|\{\{/);
  });
});

// ─── 3. Packaging — it really reaches the consumer ────────────────────

describe('packaging — the published tarball carries the file', () => {
  it('npm pack includes canonical-notes.json, byte-identical to the repo copy', () => {
    const dir = mkdtempSync(join(tmpdir(), 'af-canon-pack-'));
    try {
      const out = execFileSync(
        'npm',
        ['pack', '--json', '--pack-destination', dir, '--ignore-scripts'],
        { cwd: ROOT, encoding: 'utf-8', maxBuffer: 64 * 1024 * 1024 },
      );
      const [{ filename }] = JSON.parse(out) as [{ filename: string }];
      const tarball = join(dir, filename);

      // Read the ONE member straight out of the archive: what a consumer
      // installing from the registry gets, not what the working tree has.
      const packed = execFileSync('tar', ['-xzOf', tarball, `package/${PUBLISHED_PATH}`], {
        encoding: 'utf-8',
        maxBuffer: 16 * 1024 * 1024,
      });
      expect(packed).toBe(readFileSync(JSON_PATH, 'utf-8'));
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }, 300_000);

  it('the files whitelist names it, and the exports map resolves it', () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8')) as {
      files: readonly string[];
      exports: Record<string, unknown>;
    };
    // Two separate promises. `files` is what SHIPS; the exports map is what a
    // Node consumer may `require.resolve` — Node's exports map is exhaustive,
    // so without the entry the path does not resolve at all, which is the
    // wrong-door failure this whole unit exists to close.
    expect(pkg.files).toContain(PUBLISHED_PATH);
    expect(pkg.exports[`./${PUBLISHED_PATH}`]).toBe(`./${PUBLISHED_PATH}`);
  });
});

// ─── 4. Documentation — the promise a reader acts on ──────────────────

describe('documentation — the published path and the Python example are real', () => {
  const page = readFileSync(join(ROOT, 'docs-next/content/docs/build/tools.mdx'), 'utf-8');

  it('the page names the file at the path the package actually publishes', () => {
    expect(page).toContain(`agentfootprint/${PUBLISHED_PATH}`);
  });

  it('the Python example reads a key that exists', () => {
    // The example is `json.load(...)["notes"]["ABSENCE_NOTE"]`. If either key
    // were renamed, the docs would teach a KeyError.
    expect(page).toContain('json.load');
    expect(page).toContain('"notes"');
    expect(page).toContain('ABSENCE_NOTE');
    expect(load().notes.ABSENCE_NOTE).toBeDefined();
  });
});

// ─── 5. Regression — drift stays impossible, not merely unlikely ──────

describe('regression — the generator is wired into the build', () => {
  it('npm run build regenerates the file, so a constant edit cannot ship stale', () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8')) as {
      scripts: Record<string, string>;
    };
    expect(pkg.scripts.build).toContain('scripts/gen-canonical-notes.mjs');
    // AFTER postbuild-esm: the generator reads dist/esm, which is only true
    // ESM once postbuild has written its package.json marker.
    expect(pkg.scripts.build.indexOf('gen-canonical-notes')).toBeGreaterThan(
      pkg.scripts.build.indexOf('postbuild-esm'),
    );
  });
});
