/**
 * Two PUBLIC test certificates (no private key is kept anywhere): a CA with
 * `basicConstraints CA:TRUE`, and a leaf it issued (`CA:FALSE`) — for the
 * `ldapDirectory` boot check that a CA file holds a CA (review idI57 N-10).
 */

export const TEST_CA_PEM = `-----BEGIN CERTIFICATE-----
MIIBnzCCAUWgAwIBAgIUKoYjINg3yC45nwiWLzCFN0LbQegwCgYIKoZIzj0EAwIw
HDEaMBgGA1UEAwwRVGVzdCBEaXJlY3RvcnkgQ0EwIBcNMjYwOTI2MDYyNjM5WhgP
MjEyNjA5MDIwNjI2MzlaMBwxGjAYBgNVBAMMEVRlc3QgRGlyZWN0b3J5IENBMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjAPrPD2CDOq+I3xYohCKXU6W8izZeCaS
N2rv7DPYt54SBUpOsbG8lSxLoAnZxMN0yvNFby8YYnihC991Z1CRQqNjMGEwHQYD
VR0OBBYEFBYxUvmUAWClpPxviDx8PkPLih1kMB8GA1UdIwQYMBaAFBYxUvmUAWCl
pPxviDx8PkPLih1kMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMAoG
CCqGSM49BAMCA0gAMEUCIGVfDQ0WqgxHZaeG8MzBlsr6Vcez45HFDSc3uZsx66e3
AiEAn72/UFiDyehT7FxzfeUrxjz1TI8/YzkSviGiroSBol8=
-----END CERTIFICATE-----
`;

export const TEST_LEAF_PEM = `-----BEGIN CERTIFICATE-----
MIIBpjCCAUugAwIBAgIUB5wZABOnjo7TPa8p+HaMzDTARXswCgYIKoZIzj0EAwIw
HDEaMBgGA1UEAwwRVGVzdCBEaXJlY3RvcnkgQ0EwIBcNMjYwOTI2MDYyNjM5WhgP
MjEyNjA5MDIwNjI2MzlaMBsxGTAXBgNVBAMMEGRjMS5jb3JwLmV4YW1wbGUwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAASPkfMViMyQ6zm4LoRJP4eZvFRYnl+H/qYQ
LQUAMgNBbEB9B1451hJJFSdeIPs8JC6M+pKTNge5uRzcN/5TzfdVo2owaDAJBgNV
HRMEAjAAMBsGA1UdEQQUMBKCEGRjMS5jb3JwLmV4YW1wbGUwHQYDVR0OBBYEFK4j
3xqUSzOxn37MZ900+T6yiHB0MB8GA1UdIwQYMBaAFBYxUvmUAWClpPxviDx8PkPL
ih1kMAoGCCqGSM49BAMCA0kAMEYCIQDvX4BkQTyhSXtJ9IZDzts8xxAMcOsfnT63
TwYnDHkK6wIhAL62CLm24j8o+FVpRL/+Vb9OlCZzxpjEiO02gTbQNr+p
-----END CERTIFICATE-----
`;
